Repository BallAerospace/COSMOS, pull requests merged in 2022-04, with the labels that each got.

#1501 Add defaults to SYSTEM META command packet
  lib/cosmos/system/system.rb
  spec/packets/commands_spec.rb
  spec/system/system_spec.rb
Labels: bug, cosmos4

#1528 update browserlistrc
  cosmos-init/clean_node_modules.bat
  cosmos-init/plugins/cosmosc2-tool-base/.browserslistrc
  cosmos-init/plugins/cosmosc2-tool-base/package.json
  cosmos-init/plugins/cosmosc2-tool-base/yarn.lock
  cosmos-init/plugins/packages/cosmosc2-demo/.browserslistrc
  cosmos-init/plugins/packages/cosmosc2-tool-admin/.browserslistrc
  cosmos-init/plugins/packages/cosmosc2-tool-autonomic/.browserslistrc
  cosmos-init/plugins/packages/cosmosc2-tool-calendar/.browserslistrc
  cosmos-init/plugins/packages/cosmosc2-tool-cmdsender/.browserslistrc
  cosmos-init/plugins/packages/cosmosc2-tool-cmdtlmserver/.browserslistrc
  cosmos-init/plugins/packages/cosmosc2-tool-common/.browserslistrc
  cosmos-init/plugins/packages/cosmosc2-tool-dataextractor/.browserslistrc
  cosmos-init/plugins/packages/cosmosc2-tool-dataviewer/.browserslistrc
  cosmos-init/plugins/packages/cosmosc2-tool-limitsmonitor/.browserslistrc
  cosmos-init/plugins/packages/cosmosc2-tool-packetviewer/.browserslistrc
  cosmos-init/plugins/packages/cosmosc2-tool-scriptrunner/.browserslistrc
  cosmos-init/plugins/packages/cosmosc2-tool-tablemanager/.browserslistrc
  cosmos-init/plugins/packages/cosmosc2-tool-tlmgrapher/.browserslistrc
  cosmos-init/plugins/packages/cosmosc2-tool-tlmviewer/.browserslistrc
  cosmos-init/plugins/yarn.lock
  cypress/.browserlistrc
Labels: bug, cosmos5

#1515 allow user to view unknown packet
  .gitignore
  cosmos-init/plugins/packages/cosmosc2-tool-admin/src/tools/CosmosAdmin/tabs/PluginsTab.vue
  cosmos-init/plugins/packages/cosmosc2-tool-cmdtlmserver/src/tools/CmdTlmServer/CmdPacketsTab.vue
  cosmos-init/plugins/packages/cosmosc2-tool-cmdtlmserver/src/tools/CmdTlmServer/InterfacesTab.vue
  cosmos-init/plugins/packages/cosmosc2-tool-cmdtlmserver/src/tools/CmdTlmServer/RoutersTab.vue
  cosmos-init/plugins/packages/cosmosc2-tool-cmdtlmserver/src/tools/CmdTlmServer/TargetsTab.vue
  cosmos-init/plugins/packages/cosmosc2-tool-cmdtlmserver/src/tools/CmdTlmServer/TlmPacketsTab.vue
  cosmos-init/plugins/packages/cosmosc2-tool-common/src/components/TargetPacketItemChooser.vue
  cosmos-init/plugins/packages/cosmosc2-tool-dataextractor/src/tools/DataExtractor/DataExtractor.vue
  cosmos-init/plugins/packages/cosmosc2-tool-dataviewer/src/tools/DataViewer/AddComponentDialog.vue
  cosmos-init/plugins/packages/cosmosc2-tool-dataviewer/src/tools/DataViewer/DataViewer.vue
  playwright/tests/data-extractor.spec.ts
  playwright/tests/data-viewer.spec.ts
Labels: cosmos5

#1543 metadata controller tests update
  cosmos-cmd-tlm-api/spec/controllers/metadata_controller_spec.rb
Labels: cosmos5

#1549 update status badges
  README.md
Labels: cosmos5

#1554 Calendar playwright tests
  cosmos-init/plugins/packages/cosmosc2-tool-calendar/src/tools/Calendar/CalendarToolbar.vue
  cosmos-init/plugins/packages/cosmosc2-tool-calendar/src/tools/Calendar/Dialogs/ActivityCreateDialog.vue
  cosmos-init/plugins/packages/cosmosc2-tool-calendar/src/tools/Calendar/Dialogs/ActivityUpdateDialog.vue
  cosmos-init/plugins/packages/cosmosc2-tool-calendar/src/tools/Calendar/Dialogs/MetadataCreateDialog.vue
  cosmos-init/plugins/packages/cosmosc2-tool-calendar/src/tools/Calendar/Dialogs/MetadataUpdateDialog.vue
  cosmos-init/plugins/packages/cosmosc2-tool-calendar/src/tools/Calendar/Dialogs/NarrationCreateDialog.vue
  cosmos-init/plugins/packages/cosmosc2-tool-calendar/src/tools/Calendar/Dialogs/NarrationUpdateDialog.vue
  cosmos-init/plugins/packages/cosmosc2-tool-calendar/src/tools/Calendar/Dialogs/TimelineCreateDialog.vue
  cosmos-init/plugins/packages/cosmosc2-tool-calendar/src/tools/Calendar/Forms/MetadataInputForm.vue
  playwright/README.md
  playwright/tests/calendar.spec.ts
Labels: cosmos5
